<?php

require_once __DIR__ . '/vendor/autoload.php';

function neo4j_connector_init() {
}

function neo4j_connector_menu() {
  return array(
    'node/%node/graph' => array(
      'type' => MENU_LOCAL_TASK,
      'title' => 'Graph info',
      'page callback' => 'neo4j_connector_node_graph_info_page',
      'page arguments' => array(1),
      'file' => 'neo4j_connector.pages.inc',
      'access callback' => TRUE,
    ),
    'neo4j/console' => array(
      'title' => 'Neo4J db console',
      'page callback' => 'neo4j_connector_console_page',
      'file' => 'neo4j_connector.pages.inc',
      'access callback' => TRUE,
    ),
  );
}

function neo4j_connector_node_insert($node) {
  Neo4JDrupal::sharedInstance()->addEntity($node, 'node');
}

function neo4j_connector_node_delete($node) {
  Neo4JDrupal::sharedInstance()->deleteEntity($node, 'node');
}

function neo4j_connector_node_update($node) {
  Neo4JDrupal::sharedInstance()->updateEntity($node, 'node');
}

function neo4j_connector_cron() {
  // @todo delete single (not entity) entries.
}
